AppEnv:
  WEB3_PROVIDER: https://evm-rpc-http-devnet-41233.galactica.com

secretEnv:
  DUMMY: 1
  # PRIVATE_KEY: ''

repo: "Galactica-corp/faucet"
image:
  registry: 10.10.0.116:5000
  repository: galactica/faucet
  pullPolicy: Always
  # tag: latest # VERSION
imagePullSecrets: []

replicaCount: 1
nameOverride: "faucet"
fullnameOverride: "faucet"

command:
  [
    "-faucet.name", "Galactica-devnet-41233 faucet",
    "-faucet.token_symbol", "GALA",
    "-faucet.amount", "0.1",
    "-httpport", "28080",
  ]

ports: #[]
  - port: 28080
    name: faucet

services: #{}
  faucet:
    - port: 28080
      name: faucet

ingresses: #{}
  graphql-public-api: #{}
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-XSS-Protection" "1; mode=block" always;
        more_set_headers X-Frame-Options DENY always;
      # nginx.ingress.kubernetes.io/whitelist-source-range: 173.245.48.0/20, 103.21.244.0/22, 103.22.200.0/22, 103.31.4.0/22, 141.101.64.0/18, 108.162.192.0/18, 190.93.240.0/20, 188.114.96.0/20, 197.234.240.0/22, 198.41.128.0/17, 162.158.0.0/15, 104.16.0.0/13, 104.24.0.0/14, 172.64.0.0/13, 131.0.72.0/22

    hosts:
      - host: faucet-devnet-41233.galactica.com
        tlsName: faucet-devnet-41233.galactica.com # todo: put cert to k8s
        service:
          port: 28080
          name: faucet

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podSecurityContext:
  {}
  # fsGroup: 2000
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
serviceAccount:
  create: false
