apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- include "chart.customAnn" . | nindent 4 }}
data:
{{- with .Values.secretEnv }}
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
type: Opaque
{{- end -}}
